// ============================================================
// UK SIC 2007 code descriptions.
// Companies House returns numeric codes only — this map turns
// them into the official activity descriptions. Unmapped codes
// fall back to their section-level description.
// ============================================================

const SECTIONS: Record<string, string> = {
  A: 'Agriculture, forestry and fishing',
  B: 'Mining and quarrying',
  C: 'Manufacturing',
  D: 'Electricity, gas, steam and air conditioning supply',
  E: 'Water supply; sewerage, waste management and remediation activities',
  F: 'Construction',
  G: 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
  H: 'Transportation and storage',
  I: 'Accommodation and food service activities',
  J: 'Information and communication',
  K: 'Financial and insurance activities',
  L: 'Real estate activities',
  M: 'Professional, scientific and technical activities',
  N: 'Administrative and support service activities',
  O: 'Public administration and defence; compulsory social security',
  P: 'Education',
  Q: 'Human health and social work activities',
  R: 'Arts, entertainment and recreation',
  S: 'Other service activities',
  T: 'Activities of households as employers; undifferentiated goods- and services-producing activities of households',
  U: 'Activities of extraterritorial organisations and bodies',
};

const CODES: Record<string, string> = {
  // A — Agriculture
  '01110': 'Growing of cereals (except rice), leguminous crops and oil seeds',
  '01130': 'Growing of vegetables and melons, roots and tubers',
  '01410': 'Raising of dairy cattle',
  '01420': 'Raising of other cattle and buffaloes',
  '01450': 'Raising of sheep and goats',
  '01470': 'Raising of poultry',
  '01500': 'Mixed farming',
  '01610': 'Support activities for crop production',
  '02200': 'Logging',
  // B — Mining & quarrying
  '06100': 'Extraction of crude petroleum',
  '06200': 'Extraction of natural gas',
  '07100': 'Mining of iron ores',
  '07290': 'Mining of other non-ferrous metal ores',
  '08110': 'Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate',
  '08990': 'Other mining and quarrying n.e.c.',
  '09100': 'Support activities for petroleum and natural gas extraction',
  '09900': 'Support activities for other mining and quarrying',
  // C — Manufacturing
  '10110': 'Processing and preserving of meat',
  '10120': 'Processing and preserving of poultry meat',
  '10310': 'Processing and preserving of potatoes',
  '10510': 'Operation of dairies and cheese making',
  '10711': 'Manufacture of bread; manufacture of fresh pastry goods and cakes',
  '10850': 'Manufacture of prepared meals and dishes',
  '10910': 'Manufacture of prepared feeds for farm animals',
  '11010': 'Distilling, rectifying and blending of spirits',
  '11050': 'Manufacture of beer',
  '11060': 'Manufacture of malt',
  '11070': 'Manufacture of soft drinks; production of mineral waters and other bottled waters',
  '14131': "Manufacture of other men's outerwear",
  '14140': 'Manufacture of other wearing apparel and accessories',
  '16210': 'Manufacture of veneer sheets and wood-based panels',
  '16230': 'Manufacture of other builders’ carpentry and joinery',
  '18120': 'Other printing',
  '18130': 'Pre-press and pre-media services',
  '21201': 'Manufacture of pharmaceutical preparations',
  '22110': 'Manufacture of rubber tyres and tubes; construction and retreading of tyres',
  '23120': 'Manufacture of hollow glass',
  '24100': 'Manufacture of basic iron and steel and of ferro-alloys',
  '24450': 'Other non-ferrous metal production',
  '24510': 'Casting of iron',
  '25110': 'Manufacture of metal structures and parts of structures',
  '25120': 'Manufacture of doors and windows of metal',
  '25500': 'Forging, pressing, stamping and roll-forming of metal; powder metallurgy',
  '25610': 'Treatment and coating of metals',
  '25620': 'Mechanical engineering activities for other metal products',
  '25710': 'Manufacture of cutlery',
  '25990': 'Manufacture of other fabricated metal products n.e.c.',
  '26110': 'Manufacture of electronic components',
  '26200': 'Manufacture of computers and peripheral equipment',
  '26300': 'Manufacture of communication equipment',
  '26400': 'Manufacture of consumer electronics',
  '26511': 'Manufacture of measuring and testing equipment (non-electrical)',
  '26600': 'Manufacture of irradiation, electromedical and electrotherapeutic equipment',
  '26800': 'Manufacture of magnetic and optical media',
  '28110': 'Manufacture of engines and turbines (except aircraft, vehicle and cycle engines)',
  '28120': 'Manufacture of lifting and handling equipment',
  '28130': 'Manufacture of other pumps, compressors, taps and valves',
  '28990': 'Manufacture of other special-purpose machinery n.e.c.',
  '29100': 'Manufacture of motor vehicles',
  '29320': 'Manufacture of other parts and accessories for motor vehicles',
  '30110': 'Building of ships and floating structures',
  '30990': 'Manufacture of other transport equipment n.e.c.',
  '31010': 'Manufacture of office and shop furniture',
  '31090': 'Manufacture of other furniture',
  '32110': 'Manufacture of jewellery and bijouterie',
  '33110': 'Repair of fabricated metal products',
  '33120': 'Repair of machinery',
  '33130': 'Repair of electronic and optical equipment',
  '33200': 'Installation of industrial machinery and equipment',
  // D/E — Energy, water, waste
  '35110': 'Production of electricity',
  '35130': 'Distribution of electricity',
  '35220': 'Transmission of electricity',
  '35230': 'Trade of electricity',
  '35300': 'Steam and air conditioning supply',
  '36000': 'Water collection, treatment and supply',
  '37000': 'Sewerage',
  '38110': 'Operation of landfills and other waste disposal operations',
  '38310': 'Dismantling of wrecks',
  // F — Construction
  '41100': 'Development of building projects',
  '41200': 'Construction of residential and non-residential buildings',
  '42110': 'Construction of roads and motorways',
  '42910': 'Construction of water projects',
  '43120': 'Site preparation',
  '43210': 'Electrical installation',
  '43220': 'Plumbing, heat and air-conditioning installation',
  '43290': 'Other construction installation',
  '43320': 'Joinery installation',
  '43990': 'Other specialised construction activities n.e.c.',
  // G — Wholesale & retail
  '45110': 'Sale of new cars and light motor vehicles',
  '45200': 'Maintenance and repair of motor vehicles',
  '45320': 'Retail sale of automotive spare parts and accessories',
  '46100': 'Wholesale on a fee or contract basis',
  '46180': 'Agents involved in the sale of a variety of goods',
  '46340': 'Wholesale of beverages',
  '46420': 'Wholesale of clothing and footwear',
  '46490': 'Wholesale of other household goods',
  '46520': 'Wholesale of electronic and telecommunications equipment and parts',
  '46540': 'Wholesale of electrical equipment for domestic use',
  '46690': 'Wholesale of other machinery, equipment and supplies',
  '46710': 'Wholesale of solid, liquid and gaseous fuels and related products',
  '46750': 'Wholesale of chemical products',
  '47110': 'Retail sale in non-specialised stores with food, beverages or tobacco predominating',
  '47210': 'Retail sale of fruit and vegetables in specialised stores',
  '47260': 'Retail sale of tobacco products in specialised stores',
  '47300': 'Retail sale of automotive fuel in specialised stores',
  '47410': 'Retail sale of computers, peripheral units and software in specialised stores',
  '47430': 'Retail sale of audio and video equipment in specialised stores',
  '47510': 'Retail sale of textiles in specialised stores',
  '47520': 'Retail sale of hardware, paints and glass in specialised stores',
  '47610': 'Retail sale of books in specialised stores',
  '47620': 'Retail sale of newspapers and stationery in specialised stores',
  '47710': 'Retail sale of clothing in specialised stores',
  '47720': 'Retail sale of footwear and leather goods in specialised stores',
  '47730': 'Dispensing chemist in specialised stores',
  '47810': 'Retail sale via stalls and markets of food, beverages and tobacco products',
  '47910': 'Retail sale via mail order houses or via Internet',
  '47990': 'Other retail sale not in stores, stalls or markets',
  // H — Transport & storage
  '49310': 'Urban and suburban passenger land transport',
  '49410': 'Freight transport by road',
  '50100': 'Sea and coastal passenger water transport',
  '50300': 'Inland passenger water transport',
  '51101': 'Scheduled passenger air transport',
  '52101': 'Operation of warehousing facilities',
  '52219': 'Other service activities incidental to land transportation',
  '53200': 'Other transportation activities n.e.c.',
  // J — Information & communication
  '58210': 'Publishing of computer games',
  '59111': 'Motion picture production activities',
  '60100': 'Radio broadcasting',
  '60200': 'Television programming and broadcasting activities',
  '61100': 'Wired telecommunications activities',
  '61200': 'Wireless telecommunications activities',
  '61300': 'Satellite telecommunications activities',
  '61900': 'Other telecommunications activities',
  '62011': 'Computer programming activities',
  '62012': 'Business and domestic software development',
  '62090': 'Other information technology and computer service activities',
  '63110': 'Data processing, hosting and related activities',
  '63120': 'Web portals',
  '63910': 'News agency activities',
  '63990': 'Other information service activities n.e.c.',
  // K — Financial & insurance
  '64191': 'Activities of banking holding companies',
  '64192': 'Activities of banks and building societies',
  '64200': 'Activities of holding companies',
  '64201': 'Activities of investment trusts and companies',
  '64301': 'Activities of real estate investment trusts (REITs)',
  '64305': 'Activities of open-ended investment companies',
  '64921': 'Activities of mortgage finance companies',
  '64999': 'Financial intermediation not elsewhere classified',
  '65120': 'Reinsurance',
  '65201': 'Non-life insurance',
  '66191': 'Activities of mortgage advisers',
  '66220': 'Activities of insurance agents and brokers',
  '66300': 'Fund management activities',
  // L — Real estate
  '68100': 'Buying and selling of own real estate',
  '68201': 'Renting and operating of own or leased real estate',
  '68209': 'Letting and operating of own or leased real estate n.e.c.',
  '68320': 'Management of real estate on a fee or contract basis',
  // M — Professional, scientific & technical
  '69101': 'Solicitors',
  '69102': 'Barristers’ chambers',
  '69202': 'Bookkeeping activities',
  '69203': 'Accounting and auditing activities',
  '70100': 'Activities of head offices',
  '70210': 'Public relations and communication activities',
  '70221': 'Management consultancy activities other than financial management',
  '70229': 'Other management consultancy activities',
  '71111': 'Architectural activities',
  '71112': 'Urban planning and architectural activities',
  '71121': 'Engineering design activities for industrial process and production',
  '71122': 'Engineering related scientific and technical consulting activities',
  '71210': 'Technical and physical testing of materials and products',
  '72110': 'Research and experimental development on biotechnology',
  '72190': 'Other research and experimental development on natural sciences and engineering',
  '73110': 'Advertising agencies',
  '73120': 'Media representation services',
  '74201': 'Photographic activities',
  '74209': 'Other specialised photography activities',
  '74909': 'Other professional, scientific and technical activities n.e.c.',
  // N — Administrative & support
  '77110': 'Renting and leasing of cars and light motor vehicles',
  '77290': 'Rental and leasing of other personal and household goods n.e.c.',
  '78101': 'Employment placement agencies',
  '78200': 'Temporary employment agency activities',
  '80200': 'Security systems service activities',
  '81100': 'Combined facilities support activities',
  '81210': 'General cleaning of buildings',
  '82110': 'Combined office administrative service activities',
  '82990': 'Other business support service activities n.e.c.',
  // P/Q — Education, health
  '85201': 'Primary education',
  '85310': 'General secondary education',
  '85510': 'Sports and recreation education',
  '86101': 'Hospital activities',
  '86210': 'General medical practice activities',
  '86220': 'Specialist medical practice activities',
  '86300': 'Dental practice activities',
  '87100': 'Residential nursing care facilities',
  '87200': 'Residential care activities for learning disabilities, mental health and substance abuse',
  '87300': 'Residential care activities for the elderly and disabled',
  // R/S — Recreation, other services
  '90010': 'Performing arts',
  '92000': 'Gambling and betting activities',
  '93110': 'Operation of sports facilities',
  '94120': 'Activities of professional membership organizations',
  '94910': 'Activities of religious organizations',
  '96010': 'Washing and (dry-)cleaning of textile and fur products',
  '96040': 'Physical well-being activities',
  '96090': 'Other personal service activities n.e.c.',
  '99000': 'Activities of other membership organizations n.e.c.',
};

export function describeSicCode(code: string | undefined | null): string | undefined {
  if (!code) return undefined;
  const c = String(code).trim();
  if (CODES[c]) return CODES[c];
  const section = c[0]?.toUpperCase();
  return section ? SECTIONS[section] : undefined;
}
